#!/usr/bin/env bash
# List your processes
# ---------------------
# Bash script that displays a list of currently running processes.
#  1- Must show all processes, for all users, including those which might not have a TTY
#  2- Display in a user-oriented format
#  3- Show process hierarchy

ps -auxf
