#!/usr/bin/env bash
# Show your Bash PID made easy
# ------------------------------
# Bash script that displays the PID, along with the process name,
# of processes whose name contain the word bash.

pgrep -l bash
