#!/usr/bin/env bash
# Highlander
# ------------
# Bash script that displays:
#  1- To infinity and beyond indefinitely
#  2- With a sleep 2 in between each iteration
#  3- I am invincible!!! when receiving a SIGTERM signal

trap "I am invincible!!!" SIGTERM

while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
