#!/usr/bin/env bash
# If 9, say Hi! 
# ---------------
# This script is displaying "Best School" 10 times, but for
# the 9th iteration, displays Best School and then Hi on a new line.

index=1
while [ $index -le 10 ]
do
	echo "Best School"

	if [ $index -eq 9 ]
	then
		echo "Hi"
	fi

	(( index++ ))
done
