#!/usr/bin/env bash
# Superstitious numbers
# -----------------------
# displays numbers from 1 to 20 and:
#  1- displays 4 and then bad luck from China for the 4th loop iteration
#  2- displays 9 and then bad luck from Japan for the 9th loop iteration
#  3- displays 17 and then bad luck from Italy for the 17th loop iteration

index=1
while [ $index -le 20 ]
do
	echo $index
	case $index in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac

	(( index++))
done
