#!/usr/bin/env bash
# For ls
# --------
# Bash script that displays:
#  1- The content of the current directory
#  2- In a list format
#  3- Where only the part of the name after the first dash is displayed
#  4- Do not display hidden files

for file in $(ls)
do
	echo $file | cut -d "-" -f 2
done
