#!/usr/bin/env bash
# Change your home IP
# ---------------------
# Bash script that configures an Ubuntu server with the below requirements:
#  1- localhost resolves to 127.0.0.2
#  2- facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sed '$a8.8.8.8	facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
